### ISSUE TITLE
Publish the addon to a maven repository

### ISSUE THREAD

**Issue by moberwasserlechner** [florianschmitt/ext-token-field#2]
Hi,

Your addon would be used much more, if you publish the artifacts into a maven repo.

Vaadin has a maven repository with is exclusively reserved for Vaadin addons. 

```
repositories {
  maven { url = "http://maven.vaadin.com/vaadin-addons" }
}
```

As far as I know publishing there should work out of the box when uploading to the vaadin directory. Maybe your addon zip misses something they need.

See these links for hints
https://vaadin.com/directory/help/creating-vaadin-add-ons
https://dev.vaadin.com/wiki/VaadinAddon

BR,
Michael

**Comment by florianschmitt** [comment]
Hey Michael, 
thanks thats a good idea, I tried it from the beginning but sadly its not working. Pushing directly to the addon repository is not working:

```
:publishMavenPublicationToMavenRepository
Upload http://maven.vaadin.com/vaadin-addons/com/explicatis/ext-token-field/0.1.2/ext-token-field-0.1.2.jar
Could not transfer artifact com.explicatis:ext-token-field:jar:0.1.2 from/to remote (http://maven.vaadin.com/vaadin-addons): Could not write to resource 'com/explicatis/ext-token-field/0.1.2/ext-token-field-0.1.2.jar'
```

I think its not allowed to work on the repo without authorization. 

So yesterday I tried to fulfill all the requirements and noticed I missed a pom.xml in the jar (META-INF/maven/[groupId]/[artifactId]/pom.xml). But adding it didn't solve the problem. Maybe Im missing something again, but I did everything the links asked me to do. I wanted to use gradle and so I used a gradle config from another add-on (PasswordField) as source. Since it was created by a Vaadin employee, maybe he uploaded it to the repo directly, because his jar-file does not include any pom.xml.

Only to get things straight, I am under the impression, that adding new versions (i.e. uploading a zip-file) to the Vaadin directory automatically adds the add-on to the maven add-on repository, if the  requirements (as pom.xml inside the jar) are fulfilled.

**Comment by moberwasserlechner** [comment]
Hi Florian,

> I think its not allowed to work on the repo without authorization.

I expected that you could not publish your addon to the vaadin repo yourself. I wouldn't allow that either ;).

> Only to get things straight, I am under the impression, that adding new versions (i.e. uploading a zip-file) to the Vaadin directory automatically adds the add-on to the maven add-on repository, if the requirements (as pom.xml inside the jar) are fulfilled.

I though so too.

But I search in the vaadin forum and got a few links, which might help
- https://vaadin.com/forum/#!/thread/8695287/8695286
- https://vaadin.com/forum/#!/thread/314556/314555
- https://vaadin.com/forum#!/thread/209228

You also should have a look at the Vaadin Gradle plugin. https://github.com/johndevs/gradle-vaadin-plugin

```
plugins {
  id "fi.jasoft.plugin.vaadin" version "0.10.4"
}
```

It's a great plugin because it handles most/all of the Vaadin related build stuff and it can create a zip file compatible with the Vaadin directory.

Anyway. I'm about to finish a addon by myself and have to deal with the same problem. I would prefer to publish my artifacts to https://bintray.com/ because its much easier to use from Gradle.

**Comment by florianschmitt** [comment]
Hi Michael, 

thanks for your effort. I know the plugin, but somehow in the past it wasn't working as I needed so I tend to write my own gradle code. I gave it a try but it didn't do anything which I already had done before on my own [as you can see here](https://github.com/johndevs/gradle-vaadin-plugin/blob/master/src/main/groovy/fi/jasoft/plugin/tasks/CreateDirectoryZipTask.groovy) 
I noticed that maybe the included pom.xml needs a repository link to the vaadin addon repository, I will try that later. 
We use a nexus and we have trouble proxing the repository anyways, so maybe another way would be preferable.

**Comment by florianschmitt** [comment]
Wow, after some iterations I got it. 
- pom.xml is not needed at all
- MANIFEST.MF must be in the jar and in the zip
- the zip's MANIFEST.MF must specify the name of the addon jar ("Vaadin-Addon: ...jar")

> A zip file must specify the location of the add-on jar if there is an add-on jar
> [https://dev.vaadin.com/wiki/VaadinAddon](url)

thats what I was missing, duh...
